"""initial_schema

Revision ID: 3e3424f16eb1
Revises: 
Create Date: 2026-06-23 16:46:56.865341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3424f16eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('wazuh_rule_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dpo_name', sa.String(length=255), nullable=False),
    sa.Column('dpo_email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('cert_in_email', sa.String(length=255), nullable=True),
    sa.Column('cert_in_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_profile_id'), 'org_profile', ['id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attack_type')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severityenum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'contained', 'resolved', 'closed', name='statusenum'), nullable=False),
    sa.Column('breach_type', sa.Enum('ransomware', 'phishing', 'unauthorized_access', 'exfiltration', 'insider', name='breachtypeenum'), nullable=False),
    sa.Column('data_categories', sa.String(length=255), nullable=True),
    sa.Column('persons_affected', sa.Integer(), nullable=True),
    sa.Column('breach_est_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('alert_id', sa.String(length=50), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_mitre', sa.String(length=20), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbook_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('linux_cmd', sa.Text(), nullable=True),
    sa.Column('windows_cmd', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=30), nullable=False),
    sa.Column('playbook_step_id', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['playbook_step_id'], ['playbook_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('case_steps')
    op.drop_table('playbook_steps')
    op.drop_table('cases')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_org_profile_id'), table_name='org_profile')
    op.drop_table('org_profile')
    op.drop_table('alerts')
    # ### end Alembic commands ###
